name: childchamp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  lottie: ^2.1.0
  flutter_animate: ^2.1.0
#  sizer: ^2.0.15
  just_audio: ^0.9.31

  # FIREBASE
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  cloud_firestore: ^4.3.1

  # PACKAGE INFO
  package_info_plus: ^3.0.2

  # OPEN PLAY STORE OR APP STORE
  open_store: ^0.5.0

  # ADS
  google_mobile_ads: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/
    - assets/images/english/
    - assets/images/hindi/
    - assets/images/gujrati/
    - assets/icons/
    - assets/sound/
